export const LOADING = 'LOADING'

export const PHONE_VERIFICATION_RECEIVED = 'PHONE_VERIFICATION_RECEIVED'
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED'
export const USER_AUTHENTICATION_ERROR = 'USER_AUTHENTICATION_ERROR'
export const PHONE_VERIFIED = 'PHONE_VERIFIED'
export const LOGOUT = 'LOGOUT'


export const COMPOSE_MESSAGE_TEXT = 'COMPOSE_MESSAGE_TEXT'
export const GOLD_MESSAGE_SENDING = 'GOLD_MESSAGE_SENDING'
export const GOLD_MESSAGE_SENT = 'GOLD_MESSAGE_SENT'
export const GOLD_MESSAGE_SENT_FAILED = 'GOLD_MESSAGE_SENT_FAILED'
export const RESET_COMPOSE_MESSAGE = 'RESET_COMPOSE_MESSAGE'
export const UPDATE_PHONE_NUMBER = 'UPDATE_PHONE_NUMBER'
export const CLEAR_ERROR = 'CLEAR_ERROR'


export const REFRESHING_INBOX = 'REFRESHING_INBOX'
export const REFRESHING_INBOX_ERROR = 'REFRESHING_INBOX_ERROR'
export const INBOX_REFRESHED = 'INBOX_REFRESHED'

export const SENT_GOLD_MESSAGES_LOADING = 'SENT_GOLD_MESSAGES_LOADING'
export const SENT_GOLD_MESSAGES_RECEIVED = 'SENT_GOLD_MESSAGES_RECEIVED'
export const SENT_GOLD_MESSAGES_ERROR = 'SENT_GOLD_MESSAGES_ERROR'

export const SELECTED_USER = 'SELECTED_USER'
export const SELECTED_USER_GOLD_MESSAGES_LOADING = 'SELECTED_USER_GOLD_MESSAGES_LOADING'
export const SELECTED_USER_GOLD_MESSAGES = 'SELECTED_USER_GOLD_MESSAGES'


export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE'
export const LOAD_USER_PROFILE_COMPLETE = 'LOAD_USER_PROFILE_COMPLETE'
export const LOAD_USER_PROFILE_ERROR = 'LOAD_USER_PROFILE_ERROR'

export const SELECTED_SENT_GOLD_MESSAGE = 'SELECTED_SENT_GOLD_MESSAGE'

export const MULTIPLE_GOLD_MESSAGES = 'MULTIPLE_GOLD_MESSAGES'
export const MULTIPLE_GOLD_MESSAGES_CLEARED = 'MULTIPLE_GOLD_MESSAGES_CLEARED'


export const INBOX_SNAPSHOT_UNSUBSCRIBE = 'INBOX_SNAPSHOT_UNSUBSCRIBE'