export const LOADING = 'LOADING'

export const PHONE_VERIFICATION_RECEIVED = 'PHONE_VERIFICATION_RECEIVED'
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED'
export const USER_AUTHENTICATION_ERROR = 'USER_AUTHENTICATION_ERROR'
export const PHONE_VERIFIED = 'PHONE_VERIFIED'


export const COMPOSE_MESSAGE_TEXT = 'COMPOSE_MESSAGE_TEXT'
export const GOLD_MESSAGE_SENDING = 'GOLD_MESSAGE_SENDING'
export const GOLD_MESSAGE_SENT = 'GOLD_MESSAGE_SENT'
export const GOLD_MESSAGE_SENT_FAILED = 'GOLD_MESSAGE_SENT_FAILED'
export const RESET_COMPOSE_MESSAGE = 'RESET_COMPOSE_MESSAGE'
export const CLEAR_ERROR = 'CLEAR_ERROR'


export const REFRESHING_INBOX = 'REFRESHING_INBOX'
export const REFRESHING_INBOX_ERROR = 'REFRESHING_INBOX_ERROR'
export const INBOX_REFRESHED = 'INBOX_REFRESHED'