export const LOADING = 'LOADING'

export const PHONE_VERIFICATION_RECEIVED = 'PHONE_VERIFICATION_RECEIVED'
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED'
export const USER_AUTHENTICATION_ERROR = 'USER_AUTHENTICATION_ERROR'
export const PHONE_VERIFIED = 'PHONE_VERIFIED'


export const COMPOSE_MESSAGE_TEXT = 'COMPOSE_MESSAGE_TEXT'